Params fixes

diff --git a/scripts/darwin-run b/scripts/darwin-run
--- a/scripts/darwin-run
+++ b/scripts/darwin-run
@@ -19,7 +19,7 @@ REVERSE_RANKS="n"
 PARTITION="scaling"
 HYPERTHREADING=false
 OPENMP_ONLY=false
-WEAK_SCALE_ONLY="n"
+WEAK_SCALE_ONLY=""
 THREAD_FLAG="n"
 COMPILER="intel"
 CXX_VERSION=0.0.0
@@ -31,27 +31,27 @@ USER=""
 MPI_VERSION=2.1.5
 BOOST_VERSION=1.68.0
 SOURCE_DIR="$(pwd)/.."
-TEST_DATA="../test_data"
+DATA_DIR="../test_data"
 BUILD_DIR=""
 BUILD_SCRIPT="darwin-build"
 
 # Remap params
 APP=""
 MPI_ARGS=""
-DIMENSION=3
+DIMENSION=0
 SOURCE_SIZE=0
-SOURCE_MAX=40
+SOURCE_MAX=0
 TARGET_SIZE=0
-TARGET_MAX=120
-SOURCE_FILE="${TEST_DATA}"
-TARGET_FILE="${TEST_DATA}"
-ENTITY_KIND="cell"
+TARGET_MAX=0
+ENTITY_KIND=""
 FIELD=""
-MATER_FIELD="'x','y','z'"
+MATER_FIELD=""
+SOURCE_FILE=""
+TARGET_FILE=""
 MATER_FILE=""
-IS_ALL_CONVEX="n"
-IS_CONFORMAL="n"
-REMAP_ORDER=2
+IS_CONVEX=""
+IS_CONFORMAL=""
+REMAP_ORDER=0
 FIELD_ORDER=0
 RESULT_FILE=""
 
@@ -91,7 +91,6 @@ print_usage() {
   echo -e "  -m, --material-field $_STRING material field function"    
   echo -e "  -z, --material-file $_PATH    material field file"    
   echo -e "  -k, --entity $_CHOICE         remap entity kind [cell|node]"    
-  echo -e "  -l, --result $_PATH           result file path"    
   echo -e "  -o, --order $_INT             interpolation order"    
   echo -e "  -i, --conform                 conformal meshes"   
   echo -e "  -x, --convex                  convex polygons"   
@@ -126,7 +125,7 @@ print_params() {
       echo -e "- target_file: \e[32m${TARGET_FILE}\e[0m"
       echo -e "- material_field: \e[32m${MATER_FIELD}\e[0m"
       echo -e "- material_file: \e[32m${MATER_FILE}\e[0m"
-      echo -e "- convex: \e[32m${IS_ALL_CONVEX}\e[0m"
+      echo -e "- convex: \e[32m${IS_CONVEX}\e[0m"
       echo -e "- entity_kind: \e[32m${ENTITY_KIND}\e[0m"
       echo -e "- interpolation order: \e[32m${REMAP_ORDER}\e[0m"
       echo -e "- results_file: \e[32m${RESULT_FILE}\e[0m";;
@@ -142,14 +141,14 @@ print_params() {
       echo -e "- field order: \e[32m${FIELD_ORDER}\e[0m";;
     (*)
       echo -e "- dimension: \e[32m${DIMENSION}\e[0m"
-      [ "${SOURCE_FILE}" != "${TEST_DATA}" ] && \
+      [ "${SOURCE_FILE}" != "" ] && \
         echo -e "- source_file: \e[32m${SOURCE_FILE}\e[0m" || \
         echo -e "- source_cells: \e[32m${SOURCE_MAX}\e[0m"
-      [ "${TARGET_FILE}" != "${TEST_DATA}" ] && \
+      [ "${TARGET_FILE}" != "" ] && \
         echo -e "- target_file: \e[32m${TARGET_FILE}\e[0m" || \
         echo -e "- target_cells: \e[32m${TARGET_MAX}\e[0m"
       echo -e "- field: \e[32m${FIELD}\e[0m"
-      echo -e "- convex: \e[32m${IS_ALL_CONVEX}\e[0m"
+      echo -e "- convex: \e[32m${IS_CONVEX}\e[0m"
       echo -e "- conformal: \e[32m${IS_CONFORMAL}\e[0m"
       echo -e "- material_field: \e[32m${MATER_FIELD}\e[0m"
       echo -e "- entity_kind: \e[32m${ENTITY_KIND}\e[0m"
@@ -160,38 +159,48 @@ print_params() {
 
 check_params() {
 
-  # number of nodes
+  # invalid number of nodes
   if [[ ! "${MAX_NODES}" =~ ^[0-9]+$ ]] || (( ${MAX_NODES} < 1 )); then
     echo -e "\e[31mError: invalid number of nodes\e[0m"
     exit 1
+  # invalid rank per node
   elif [[ ! "${RANKS_PER_NODE}" =~ ^[0-9]+$ ]] \
        || (( ${RANKS_PER_NODE} < 1 )) || (( ${RANKS_PER_NODE} > ${CORES})); then
-    echo -e "\e[31mError: invalid MPI rank per node value\e[0m"
+    echo -e "\e[31mError: invalid rank per node value\e[0m"
     exit 1
+  # unsupported compiler
   elif [ "${COMPILER}" != "intel" ] && [ "${COMPILER}" != "gcc" ]; then
-    echo -e "\e[31mError: unsupported compiler '${COMPILER}' [intel|gcc]\e[0m"
+    echo -e "\e[31mError: unsupported compiler '${COMPILER}'\e[0m"
     exit 1
+  # invalid mesh dimension
   elif [[ ! "${DIMENSION}" =~ ^[2-3]$ ]]; then 
     echo -e "\e[31mError: invalid mesh dimension [2|3]\e[0m"
     exit 1
-  elif [[ ! "${SOURCE_MAX}" =~ ^[0-9]+$ ]] || (( ${SOURCE_MAX} < 1)); then
-    echo -e "\e[31mError: invalid number of source cells\e[0m"
+  # neither a source exodus file nor a source cells extent supplied
+  elif [ ! -f ${SOURCE_FILE} ] && { [[ ! "${SOURCE_MAX}" =~ ^[0-9]+$ ]] || (( ${SOURCE_MAX} < 1)); }; then
+    echo -e "\e[31mError: invalid source file or cells count\e[0m"
     exit 1 
-  elif [[ ! "${TARGET_MAX}" =~ ^[0-9]+$ ]] || (( ${TARGET_MAX} < 1)); then
-    echo -e "\e[31mError: invalid number of target cells\e[0m"
+  # neither a target exodus file nor a target cells extent supplied
+  elif [ ! -f ${TARGET_FILE} ] && { [[ ! "${TARGET_MAX}" =~ ^[0-9]+$ ]] || (( ${TARGET_MAX} < 1)); }; then
+    echo -e "\e[31mError: invalid target file or cells count\e[0m"
     exit 1
-  elif [ "${SOURCE_FILE}" != "${TEST_DATA}" ] && [ ! -f ${SOURCE_FILE} ]; then
+  # mandatory source file
+  elif { [ ${SOURCE_MAX} -eq 0 ] || [ "${APP}" = "multimat" ]; } && [ ! -f ${SOURCE_FILE} ]; then
     echo -e "\e[31mError: invalid source file '${SOURCE_FILE}'\e[0m"
     exit 1
-  elif [ "${TARGET_FILE}" != "${TEST_DATA}" ] && [ ! -f ${TARGET_FILE} ]; then
+  # mandatory target file
+  elif { [ ${TARGET_MAX} -eq 0 ] || [ "${APP}" = "multimat" ]; } && [ ! -f ${TARGET_FILE} ]; then
     echo -e "\e[31mError: invalid target file '${TARGET_FILE}'\e[0m"
     exit 1
+  # unknown entity kind
   elif [ "${ENTITY_KIND}" != "cell" ] && [ "${ENTITY_KIND}" != "node" ]; then
     echo -e "\e[31mError: invalid '${ENTITY_KIND}' entity kind\e[0m"
     exit 1
+  # invalid interpolation order
   elif [[ ! "${REMAP_ORDER}" =~ ^[1-2]$ ]]; then
     echo -e "\e[31mError: invalid remap order [1-2]\e[0m"
     exit 1 
+  # invalid field order
   elif [[ ! "${FIELD_ORDER}" =~ ^[0-2]$ ]]; then
     echo -e "\e[31mError: invalid field order [0-2]\e[0m"
     exit 1 
@@ -203,57 +212,56 @@ check_params() {
 
 set_default_params() {
 
-  if [ "$#" -ne 1 ]; then
-    echo -e "\e[31mError: please supply the app name\e[0m"
-    exit 1
-  fi
-
-  # set default params
-  case "$1" in
+  # todo: check if set and process only if not
+  case "${APP}" in
     core)
       echo "Setting portage core rect_3d_cell_f0_r1"
-      DIMENSION=3
-      SOURCE_MAX=40
-      TARGET_MAX=120
-      IS_CONFORMAL="y"
-      FIELD="73.98"
-      ENTITY_KIND="cell"
-      REMAP_ORDER=1
-      RESULT_FILE="jali_rect_3d_cell_f0_r1.txt";;
+      [ "${DIMENSION}" -eq 0 ] && DIMENSION=3
+      [ "${SOURCE_MAX}" -eq 0 ] && SOURCE_MAX=40
+      [ "${TARGET_MAX}" -eq 0 ] && TARGET_MAX=120
+      [ "${IS_CONFORMAL}" != "" ] || IS_CONFORMAL="y"
+      [ "${FIELD}" != "" ] || FIELD="73.98"
+      [ "${ENTITY_KIND}" != "" ] || ENTITY_KIND="cell"
+      [ "${REMAP_ORDER}" -eq 0 ] && REMAP_ORDER=1
+      [ "${RESULT_FILE}" != "" ] || RESULT_FILE="jali_rect_3d_cell_f0_r1.txt";;
     t-junction)
       echo "Setting t-junction default params"
-      DIMENSION=3
-      SOURCE_MAX=40
-      TARGET_MAX=120
-      IS_CONFORMAL="y"
-      MATER_FIELD="'x','y','z'"
-      REMAP_ORDER="2";;
+      [ "${DIMENSION}" -eq 0 ] && DIMENSION=3
+      [ "${SOURCE_MAX}" -eq 0 ] && SOURCE_MAX=40
+      [ "${TARGET_MAX}" -eq 0 ] && TARGET_MAX=120
+      [ "${ENTITY_KIND}" != "" ] || ENTITY_KIND="cell"
+      [ "${IS_CONFORMAL}" != "" ] || IS_CONFORMAL="y"
+      [ "${IS_CONVEX}" != "" ] || IS_CONVEX="y"
+      [ "${MATER_FIELD}" != "" ] || MATER_FIELD="'x','y','z'"
+      [ "${REMAP_ORDER}" -eq 0 ] && REMAP_ORDER="2";;
     multimat)
       echo "Setting multimat unstruct_2d_cell_f1_r2"
-      DIMENSION=2
-      SOURCE_FILE="${TEST_DATA}/reg10x10.exo"
-      TARGET_FILE="${TEST_DATA}/polymesh_10x10.exo"
-      MATER_FIELD="5*x-y,2*x+4+3*y,-2*x-y"
-      MATER_FILE="${TEST_DATA}/reg10x10.bvf"
-      RESULT_FILE="multimat_jali_unstruc_2d_cell_f1_r2.gmv";;
+      [ "${DIMENSION}" -eq 0 ] && DIMENSION=2
+      [ "${SOURCE_FILE}" != "" ] || SOURCE_FILE="${DATA_DIR}/reg10x10.exo"
+      [ "${TARGET_FILE}" != "" ] || TARGET_FILE="${DATA_DIR}/polymesh_10x10.exo"
+      [ "${ENTITY_KIND}" != "" ] || ENTITY_KIND="cell"
+      [ "${MATER_FIELD}" != "" ] || MATER_FIELD="5*x-y,2*x+4+3*y,-2*x-y"
+      [ "${MATER_FILE}" != "" ] || MATER_FILE="${DATA_DIR}/reg10x10.bvf"
+      [ "${IS_CONFORMAL}" != "" ] || IS_CONFORMAL="y"
+      [ "${IS_CONVEX}" != "" ] || IS_CONVEX="y"
+      [ "${REMAP_ORDER}" -eq 0 ] && REMAP_ORDER="2"
+      [ "${RESULT_FILE}" != "" ] || RESULT_FILE="multimat_jali_unstruc_2d_cell_f1_r2.gmv";;
     timing)
       echo "Setting timing app default params"
-      DIMENSION=2
-      SOURCE_MAX=40
-      TARGET_MAX=120
-      IS_CONFORMAL="y"
-      REVERSE_RANKS="n"
-      WEAK_SCALE_ONLY="n"
-      ENTITY_KIND="cell"
-      REMAP_ORDER=1
-      FIELD_ORDER=0;;
+      [ "${DIMENSION}" -eq 0 ] && DIMENSION=2
+      [ "${SOURCE_MAX}" -eq 0 ] && SOURCE_MAX=40
+      [ "${TARGET_MAX}" -eq 0 ] && TARGET_MAX=120
+      [ "${ENTITY_KIND}" != "" ] || ENTITY_KIND="cell"
+      [ "${IS_CONFORMAL}" != "" ] || IS_CONFORMAL="y"
+      [ "${IS_CONVEX}" != "" ] || IS_CONVEX="y"
+      [ "${REVERSE_RANKS}" != "" ] || REVERSE_RANKS="n"
+      [ "${WEAK_SCALE_ONLY}" != "" ] || WEAK_SCALE_ONLY="n"
+      [ "${REMAP_ORDER}" -eq 0 ] && REMAP_ORDER=1
+      [ "${FIELD_ORDER}" -eq 0 ] && FIELD_ORDER=0;;
     (*)
-      echo -e "\e[31mError: unsupported '$1' app\e[0m"
+      echo -e "\e[31mError: unsupported ${APP} app\e[0m"
       exit 1;;
   esac
-  
-  # store name eventually
-  APP="$1"
 }
 
 
@@ -315,7 +323,7 @@ setup_run_options() {
   fi
 }
 
-setup_app_options() {
+update_app_options() {
   APP_ARGS=() 
  
   # set app-specific argument list
@@ -369,13 +377,8 @@ setup_app_options() {
         "--remap_order=${REMAP_ORDER}"
         "--only_threads=${THREAD_FLAG}"
       );;
-    # todo: check params
-    simple_mesh)
-      APP_ARGS=( "./app/${APP}_app/${APP}_app" )
-      echo -e "\e[31mError: '${APP}' is not yet supported\e[0m"
-      exit 1;;
     (*)
-      echo -e "\e[31mError: invalid app '${APP}'\e[0m"
+      echo -e "\e[31mError: invalid or not yet supported app '${APP}'\e[0m"
       exit 1;;
   esac
 
@@ -387,17 +390,19 @@ setup_app_options() {
 }
 
 setup() {
+
   # parse options (requires GNU getopt).
-  SHORT_OPT="ha:bn:r:p:u:c:w:d:f:q:s:t:m:z:k:l:o:ixye:" 
+  SHORT_OPT="ha:b:n:r:p:u:c:w:d:f:q:s:t:m:z:k:o:ixye:" 
   LONG_OPT="help,app:,build,nodes:,ranks:,partition:,user:,compiler:,hwthreads:,"
   LONG_OPT+="dim:,field:,field-order:,source:,target:,material-field:,material-file:,"
-  LONG_OPT+="entity:,result:,order:,conform,convex,thread-only,results:"
+  LONG_OPT+="entity:,order:,conform,convex,thread-only,results:"
+  options=""
 
   # handle no option case
   if [ "$#" -eq 0 ]; then
     echo -e "\e[31mError: please specify the app at least\e[0m"
     exit 1
-  elif ! options=$(getopt -o "${SHORT_OPT}" -l "${LONG_OPT}" -- $@); then
+  elif ! options=$(getopt -o ${SHORT_OPT} -l ${LONG_OPT} -- "$@"); then
     print_usage
   fi
  
@@ -408,7 +413,7 @@ setup() {
   while [ "$#" -gt 0 ]; do
     case "$1" in
       -h|--help) print_usage;;
-      -a|--app) set_default_params "$2"; shift;;
+      -a|--app) APP="$2"; shift;;
       -b|--build) source ${BUILD_SCRIPT}; exit 0;; 
       -n|--nodes) MAX_NODES="$2"; shift;;
       -r|--ranks) RANKS_PER_NODE="$2"; shift;;
@@ -419,31 +424,30 @@ setup() {
       -d|--dim) DIMENSION="$2"; shift;;
       -f|--field) FIELD="$2"; shift;; 
       -q|--field-order) FIELD_ORDER="$2"; shift;; 
-      -s|--source) [[ "$2" =~ ^[0-9]+$ ]] && SOURCE_MAX="$2" || SOURCE_FILE+="/$2"; shift;;
-      -t|--target) [[ "$2" =~ ^[0-9]+$ ]] && TARGET_MAX="$2" || TARGET_FILE+="/$2"; shift;;
+      -s|--source) [[ "$2" =~ ^[0-9]+$ ]] && SOURCE_MAX="$2" || SOURCE_FILE="${DATA_DIR}/$2"; shift;;
+      -t|--target) [[ "$2" =~ ^[0-9]+$ ]] && TARGET_MAX="$2" || TARGET_FILE="${DATA_DIR}/$2"; shift;;
       -m|--material-field) MATER_FIELD="$2"; shift;; 
-      -z|--material-file) MATER_FILE="$2"; shift;; 
+      -z|--material-file) MATER_FILE="${DATA_DIR}/$2"; shift;; 
       -k|--entity) ENTITY_KIND="$2"; shift;; 
-      -l|--result) RESULT_FILE="$2"; shift;; 
       -o|--order) REMAP_ORDER="$2"; shift;; 
       -i|--conform) IS_CONFORMAL="y";; 
       -x|--convex) IS_CONVEX="y";; 
       -y|--thread-only) OPENMP_ONLY=true; MAX_NODES=1;; 
       -e|--results) RESULT_FILE="$2"; shift;; 
-      (--) shift; break;;
-      (-*) print_usage;;
-      (*) break;;
+      --) break;;
+      -*) print_usage;;
+      *) break;;
     esac
     shift
   done
 
+  # set default params
+  set_default_params;
+  
   # set benchmark options 
   setup_run_options
 
-  # set app specific args
-  setup_app_options
- 
-  # check all params eventually
+  # check all params
   check_params
 }
 
@@ -460,6 +464,9 @@ run_scaling() {
       SOURCE_SIZE="${SOURCE_MAX}" 
       TARGET_SIZE="${TARGET_MAX}" 
     fi
+  
+    # set app specific args
+    update_app_options
     
     # generated files
     OUTPUT="darwin_${APP}_${SCALING_TYPE}_scaling_${EXTENT}_${MODE}.log"
@@ -504,8 +511,8 @@ run_scaling() {
 
     # Run it
     echo "Running ${APP} ${SCALING_TYPE} scaling"
-    #[ "${SCALING_TYPE}" = "strong" ] && sbatch -v ${SCRIPT}
-    [ "${SCALING_TYPE}" = "strong" ] && cat ${SCRIPT}
+    [ "${SCALING_TYPE}" = "strong" ] && sbatch -v ${SCRIPT}
+    #[ "${SCALING_TYPE}" = "strong" ] && cat ${SCRIPT}
   done
 
   # check slurm allocation
