Add support for snow and grizzly

diff --git a/scripts/scaling-run b/scripts/scaling-run
--- a/scripts/scaling-run
+++ b/scripts/scaling-run
@@ -18,9 +18,9 @@ EXTENT=0
 MAX_NODES=1
 MAX_THREADS=1
 RANKS_PER_NODE=1
-HYPERTHREADS_PER_CORE=1
+THREADS_PER_CORE=1
 REVERSE_RANKS="n"
-PARTITION="scaling"
+PARTITION=""
 HYPERTHREADING=false
 OPENMP_ONLY=false
 WEAK_SCALE_ONLY=""
@@ -32,8 +32,8 @@ MODE=""
 USER=""
 
 # Version numbers
-MPI_VERSION=2.1.5
-BOOST_VERSION=1.68.0
+MPI_VERSION=""
+BOOST_VERSION=""
 SOURCE_DIR="$(pwd)/.."
 DATA_DIR="../test_data"
 BUILD_DIR=""
@@ -225,8 +225,20 @@ check_params() {
 
 set_default_params() {
 
-  [ "${CLUSTER}" != "" ] || CLUSTER="${SUPPORTED_CLUSTER[0]}"
+  # set default cluster, partition and MPI version
+  if [ "${CLUSTER}" = "" ]; then
+    CLUSTER="${SUPPORTED_CLUSTER[0]}"
+  fi
 
+  case "${CLUSTER}" in
+    darwin) PARTITION="scaling"; MPI_VERSION="2.1.5"; BOOST_VERSION="1.68.0";;
+    snow|grizzly) PARTITION="standard"; MPI_VERSION="2.1.2";;
+    *)
+      echo -e "\e[31mError: unsupported cluster ${CLUSTER}\e[0m"
+      exit 1;;
+  esac
+
+  # set app default parameters
   case "${APP}" in
     core)
       [ "${DIMENSION}" -eq 0 ] && DIMENSION=3
@@ -283,21 +295,30 @@ setup_run_options() {
   # slurm partition  
   #CORES=$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}');
   #LOG_CORES=$(nproc --all);
-  #HYPERTHREADS_PER_CORE=$((LOG_CORES / CORES));;
-  
-  case "${PARTITION}" in
-    scaling) CORES=16; HYPERTHREADS_PER_CORE=2;;
-    skylake-gold) CORES=22; HYPERTHREADS_PER_CORE=2;;
-    (*) 
-      echo -e "\e[31mError: invalid slurm partition ${PARTITION}\e[0m"
-      exit 1;;
-  esac
+  #THREADS_PER_CORE=$((LOG_CORES / CORES));;
+
+  if [ "${CLUSTER}" = "darwin" ]; then
+    case "${PARTITION}" in
+      scaling|volta-x86) CORES=16; THREADS_PER_CORE=2;;
+      skylake-gold) CORES=22; THREADS_PER_CORE=2;;
+      (*)
+        echo -e "\e[31mError: unsupported partition ${PARTITION} on ${CLUSTER}\e[0m"
+        exit 1;;
+    esac
+  else # snow|grizzly
+    case "${PARTITION}" in
+      standard|any) CORES=36; THREADS_PER_CORE=2;;
+      (*)
+        echo -e "\e[31mError: unsupported partition ${PARTITION} on ${CLUSTER}\e[0m"
+        exit 1;;
+    esac
+  fi
 
   # set CPU affinity options
   if [ "${HYPERTHREADING}" = true ]; then
     [ "COMPILER" = "intel" ] && GRAIN="fine" || GRAIN="threads"
   else
-    HYPERTHREADS_PER_CORE=1
+    THREADS_PER_CORE=1
     [ "COMPILER" = "intel" ] && GRAIN="core" || GRAIN="cores"
   fi
 
@@ -311,7 +332,7 @@ setup_run_options() {
   fi
   
   MAX_RANKS=$((MAX_NODES * RANKS_PER_NODE))  
-  MAX_THREADS=$((CORES * HYPERTHREADS_PER_CORE))
+  MAX_THREADS=$((CORES * THREADS_PER_CORE))
   
   # run dependent options
   if [ "${OPENMP_ONLY}" = true ]; then
@@ -484,42 +505,46 @@ run_scaling() {
     OUTPUT="${CLUSTER}_${APP}_${SCALING_TYPE}_scaling_${EXTENT}_${MODE}.log"
     SCRIPT="${CLUSTER}_${APP}_${SCALING_TYPE}_scaling_${EXTENT}_${MODE}.sh"
 
-    echo -e "#!/bin/bash"                                                    > ${SCRIPT}
-    echo -e ""                                                              >> ${SCRIPT}
-    echo -e "# Batch script for ${APP} ${SCALING_TYPE} scaling app"         >> ${SCRIPT}
-    echo -e "# Generated on $(date +'%Y-%m-%d %T')"                         >> ${SCRIPT}
-    echo -e ""                                                              >> ${SCRIPT}
-    echo -e "#SBATCH --time=2:00:00"                                        >> ${SCRIPT}                      
-    echo -e "#SBATCH --partition=${PARTITION}"                              >> ${SCRIPT}                      
-    echo -e "#SBATCH --nodes=${NODES}"                                      >> ${SCRIPT} 
-    echo -e "#SBATCH --ntasks-per-node=${RANKS_PER_NODE}"                   >> ${SCRIPT}
-    echo -e "#SBATCH --job-name=remap"                                      >> ${SCRIPT}
-    echo -e "#SBATCH --error=${OUTPUT}"                                     >> ${SCRIPT}
-    echo -e "#SBATCH --output=${OUTPUT}"                                    >> ${SCRIPT}
-    echo -e "#SBATCH --no-requeue"                                          >> ${SCRIPT} 
-    echo -e "#SBATCH --signal=23@60"                                        >> ${SCRIPT}                  
-    echo -e ""                                                              >> ${SCRIPT}
-    echo -e "# move to the build directory"                                 >> ${SCRIPT}
-    echo -e "cd ${BUILD_DIR}"                                               >> ${SCRIPT}
-    echo -e ""                                                              >> ${SCRIPT}
-    echo -e "# load modules"                                                >> ${SCRIPT}
-    echo -e "module load ${COMPILER}/${CXX_VERSION}"                        >> ${SCRIPT}
-    echo -e "module load openmpi/${MPI_VERSION}-${COMPILER}_${CXX_VERSION}" >> ${SCRIPT}
-    echo -e "module load boost/${BOOST_VERSION}"                            >> ${SCRIPT}
-    echo -e ""                                                              >> ${SCRIPT}
-    echo -e "# set thread-core affinity"                                    >> ${SCRIPT}
-    echo -e "export ${CPU_AFFINITY}"                                        >> ${SCRIPT}
-    echo -e ""                                                              >> ${SCRIPT}
-    echo -e "# run serial"                                                  >> ${SCRIPT}
-    echo -e "export OMP_NUM_THREADS=${INIT_THREADS}"                        >> ${SCRIPT}
-    echo -e "mpirun -n 1 ${MPI_ARGS}"                                       >> ${SCRIPT}
-    echo -e ""                                                              >> ${SCRIPT}
-    echo -e "# run parallel"                                                >> ${SCRIPT}
-    echo -e "for ((i=2; i <= ${EXTENT}; i*=2)); do"                         >> ${SCRIPT}
-    echo -e "  export OMP_NUM_THREADS=${THREADS}"                           >> ${SCRIPT}
-    echo -e "  mpirun -n ${RANKS} ${MPI_ARGS}"                               >> ${SCRIPT}
-    echo -e "done"                                                          >> ${SCRIPT}
-    echo -e "# ========================================================"    >> ${SCRIPT}
+    echo -e "#!/bin/bash"                                                      > ${SCRIPT}
+    echo -e ""                                                                >> ${SCRIPT}
+    echo -e "# Batch script for ${APP} ${SCALING_TYPE} scaling app"           >> ${SCRIPT}
+    echo -e "# Generated on $(date +'%Y-%m-%d %T')"                           >> ${SCRIPT}
+    echo -e ""                                                                >> ${SCRIPT}
+    echo -e "#SBATCH --time=2:00:00"                                          >> ${SCRIPT}
+    echo -e "#SBATCH --partition=${PARTITION}"                                >> ${SCRIPT}
+    echo -e "#SBATCH --nodes=${NODES}"                                        >> ${SCRIPT}
+    echo -e "#SBATCH --ntasks-per-node=${RANKS_PER_NODE}"                     >> ${SCRIPT}
+    echo -e "#SBATCH --job-name=remap"                                        >> ${SCRIPT}
+    echo -e "#SBATCH --error=${OUTPUT}"                                       >> ${SCRIPT}
+    echo -e "#SBATCH --output=${OUTPUT}"                                      >> ${SCRIPT}
+    echo -e "#SBATCH --no-requeue"                                            >> ${SCRIPT}
+    echo -e "#SBATCH --signal=23@60"                                          >> ${SCRIPT}
+    echo -e ""                                                                >> ${SCRIPT}
+    echo -e "# move to the build directory"                                   >> ${SCRIPT}
+    echo -e "cd ${BUILD_DIR}"                                                 >> ${SCRIPT}
+    echo -e ""                                                                >> ${SCRIPT}
+    echo -e "# load modules"                                                  >> ${SCRIPT}
+    echo -e "module load ${COMPILER}/${CXX_VERSION}"                          >> ${SCRIPT}
+    if [ "${CLUSTER}" = "darwin" ]; then
+      echo -e "module load openmpi/${MPI_VERSION}-${COMPILER}_${CXX_VERSION}" >> ${SCRIPT}
+      echo -e "module load boost/${BOOST_VERSION}"                            >> ${SCRIPT}
+    else
+      echo -e "module load openmpi/${MPI_VERSION}"                            >> ${SCRIPT}
+    fi
+    echo -e ""                                                                >> ${SCRIPT}
+    echo -e "# set thread-core affinity"                                      >> ${SCRIPT}
+    echo -e "export ${CPU_AFFINITY}"                                          >> ${SCRIPT}
+    echo -e ""                                                                >> ${SCRIPT}
+    echo -e "# run serial"                                                    >> ${SCRIPT}
+    echo -e "export OMP_NUM_THREADS=${INIT_THREADS}"                          >> ${SCRIPT}
+    echo -e "mpirun -n 1 ${MPI_ARGS}"                                         >> ${SCRIPT}
+    echo -e ""                                                                >> ${SCRIPT}
+    echo -e "# run parallel"                                                  >> ${SCRIPT}
+    echo -e "for ((i=2; i <= ${EXTENT}; i*=2)); do"                           >> ${SCRIPT}
+    echo -e "  export OMP_NUM_THREADS=${THREADS}"                             >> ${SCRIPT}
+    echo -e "  mpirun -n ${RANKS} ${MPI_ARGS}"                                >> ${SCRIPT}
+    echo -e "done"                                                            >> ${SCRIPT}
+    echo -e "# ========================================================"      >> ${SCRIPT}
 
     # Run it
     echo "Running ${APP} ${SCALING_TYPE} scaling"
